<form method="post" action="index.php">
    <fieldset>
        <label for="new-name">Nom de la catégorie</label>
        <input type="text" name="new-name"/>
    </fieldset>
    <fieldset>
        <label for="new-description">Description</label>
        <textarea id="new-description" name="new-description">
                Votre description de la catégorie ...
        </textarea>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Valider"/>
    </fieldset>
    <input type="hidden" name="formCreateCategory"/>
</form>