<form method="post" action="index.php">
    <fieldset>
        <label for="edit-name">Nom de la catégorie</label>
        <input type="text" name="edit-name"/>
    </fieldset>
    <fieldset>
        <label for="edit-description">Description</label>
        <textarea id="edit-description" name="edit-description">
                Votre description de la catégorie ...
        </textarea>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Valider"/>
    </fieldset>
    <input type="hidden" name="formEditCategory"/>
</form>