<section id="post-tab">
                <h2>Liste des posts</h2>
                <section>
                    <table>
                        <thead>
                            <tr>
                                <th>
                                    id
                                </th>
                                <th>
                                    nom
                                </th>
                                <th>
                                    description
                                </th>
                            </tr>
                        </thead>
                        <tbody id="tbody-post">
                            <?php
                            foreach($postsCategoryTab as $item)
                                {
                            ?>
                            <tr>
                                <td>
                                    <?= $item->getId(); ?>
                                </td>
                                <td>
                                    <?= $item->getName();?>
                                </td>
                                <td>
                                    <?= $item->getDescription(); ?>
                                 </td>
                            </tr>
                            <?php
                                }
                            ?>
                        </tbody>
                    </table>
                    <?php
                    require '_post-category-create.phtml';
                    require '_post-category-edit.phtml';
                    ?>
                </section>

            </section>