<form action="index.php" method="post">
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="email"/>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe</label>
        <input type="password" name="password"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="Se connecter"/>
    </fieldset>
    <input id="formName" name="formName" type="hidden" value="">
</form>