<form method="post" action="index.php">
    <fieldset>
        <label for="newFirstName">First Name</label>
        <input type="text" name="newFirstName"/>
    </fieldset>
    <fieldset>
        <label for="newLastName">Last Name</label>
        <input type="text" name="newLastName"/>
    </fieldset>
    <fieldset>
        <label for="newEmail">Email</label>
        <input type="email" name="newEmail"/>
    </fieldset>
    <fieldset>
        <label for="newPassword">Mot de passe</label>
        <input type="password" name="newPassword"/>
    </fieldset>
    <fieldset>
        <label for="confirm-pwd">Confirmer le mot de passe</label>
        <input type="password" name="confirm-pwd"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="S'enregistrer"/>
    </fieldset>
    <input type="hidden" name="formName"/>
</form>

